In [19]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-85, -80,  67,  17,  10, -41])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2,]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
input1 = torch.empty(2, 3)
input1

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [14]:
linespace = torch.linspace(3, 10, steps=5)
linespace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [16]:
logspase = torch.logspace(start=-10, end=10, steps=5)
logspase

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [17]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [25]:
# определить вероятность тензора
probabilities =torch.tensor([0.1, 0.9])
# Пять семплов из мультичислового распределения
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)
# Мы создали тензор с числом элементов num_samples, с вероятностью 0 - 0.1 и 1 - 0.9

tensor([1, 0, 1, 1, 0, 1, 1, 1, 1, 1])


In [26]:
# Конноктация векторов
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [27]:
# трил = треугольник нижний (triengle lower)
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [28]:
# трил = треугольник верхний (triengle upper)
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [29]:
# Маска на тензор (masked fill)
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [30]:
# взятие экспоненты по каждому элементу
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [31]:
# Транспонирование
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [33]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Соединить (состаковать) тензоры в новое измерение
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [34]:
# Мы часто будем прибегать к линейному слою нейронной сети
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-2.9059, -2.3252,  9.9791], grad_fn=<SqueezeBackward4>)


In [38]:
# На выходе нейронной сети будет располагаться функция софтмакс
# Возможно будут и другие функции
import torch.nn.functional as F

# Создадим вектор для примера
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# К этому (допустим выходному результирующему) вектору применим функцию softax
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [39]:
# Инициализируем эмбендинговый слой
vocab_size = 10_000
embedding_dim = 100
embending = nn.Embedding(vocab_size, embedding_dim)

# Создадим нектороный входной тензор
input_indices = torch.LongTensor([1, 5, 3, 2])

# Применим эмбенднинговый слой
embending_output = embending(input_indices)

# На выходе будет тензор размерностью (4, 100), где 4 - количество входов
# и 100 - это размерность вектора эмбендинга
print(embending_output.shape)

torch.Size([4, 100])


In [43]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]]) 
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [46]:
int_64 = torch.randint(1, (3, 2)).float()
# тип int 64
float_32 = torch.rand(2, 3)
# тип float 32
print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

torch.float32 torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [50]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x, y, z)
# print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


tensor([[[0.3650, 0.4064, 0.5097, 0.2530, 0.0932],
         [0.4376, 0.8699, 0.8242, 0.3018, 0.2747],
         [0.4731, 0.8557, 0.6672, 0.7980, 0.4743]],

        [[0.9842, 0.9740, 0.4500, 0.3327, 0.6538],
         [0.0905, 0.7895, 0.3073, 0.1052, 0.2910],
         [0.5539, 0.0697, 0.7893, 0.9815, 0.3979]]])